{% set name = "nPhase" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6753b5dc78f70adae89704ff1d878084a09835845848adf50e3c627eaeac3999

build:
  number: 0
  entry_points:
    - nphase = bin.nPhasePipeline:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - plotnine >=0.7.1
    - python >=3.8
    - sortedcontainers
  run:
    - plotnine >=0.7.1
    - python >=3.8
    - sortedcontainers
    - samtools==1.9
    - ngmlr
    - gatk4
    - bwa

test:
  imports:
    - bin
  commands:
    - nphase --help

about:
  home: "https://https://github.com/OmarOakheart/nPhase"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file:
  summary: "nPhase is a command line ploidy agnostic phasing pipeline and algorithm which phases samples of any ploidy with sequence alignment of long and short read data to a reference sequence."
  doc_url: https://github.com/OmarOakheart/nPhase/blob/master/README.md
  dev_url: https://github.com/OmarOakheart/nPhase

extra:
  recipe-maintainers:
    - https://github.com/OmarOakheart
